# development:
#  adapter: mysql2
#  database: reach_dev
#  username: root
#  password: root
#  pool: 50
#  timeout: 15000

development:
  adapter: sqlite3
  database: db/dev.sqlite
  pool: 50
  timeout: 15000

# test: &test
#  adapter: mysql2
#  database: reach_test
#  username: root
#  password: root
#  pool: 20
#  timeout: 15000

test: &test
  adapter: sqlite3
  database: db/test.sqlite
  pool: 20
  timeout: 15000

# production:
#   adapter: mysql2
#   database: reach
#   username: root
#   password: root
#   pool: 50
#   timeout: 15000
production:
   adapter: sqlite3
   database: db/prod.sqlite
   pool: 50
   timeout: 15000
cucumber:
  <<: *test
