development:
  adapter: mysql2
  database: reach
  username: root
  password: root
  pool: 50
  timeout: 15000

test: &test
  adapter: mysql2
  database: reach_test
  username: root
  password: root
  pool: 20
  timeout: 15000

production:
   adapter: mysql2
   database: reach
   username: root
   password: root
   pool: 50
   timeout: 15000

cucumber:
  <<: *test
